---
title: "Iteration"
author: "Yifan Shi"
date: "2024-10-24"
output: github_document
---
```{r set up, include=FALSE}
library(tidyverse)
library(rvest)
library(readxl)


knitr::opts_chunk$set(
	echo = TRUE,
	warning = FALSE,
	fig.width = 8, 
  fig.height = 6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Write my first function

z-score computation
```{r}
x_vec = rnorm(n = 25, mean = 10, sd = 3.5)

(x_vec - mean(x_vec)) / sd(x_vec)
```

now i will write a function to do this; also put conditional execution
```{r}
z_scores = function(x) {
  
  if(!is.numeric(x)){
    stop("x needs to be numeric")
  }
  
  if(length(x) < 5){
    stop("you need at least five numbers to compute the z score")
  }
  
  z = (x - mean(x)) / sd(x)
  
  return(z)
  
}

z_scores(x = x_vec)
```


does this always work?

```{r, error = TRUE}
z_scores(x = 3)
z_scores(x = c("my", "name", "is", "jeff"))

z_scores(x = x_vec)
```


# A new function, mean and sd

```{r}
mean_and_sd = function(x){
  
  mean_x = mean(x)
  sd_x = sd(x)
  
  out_df = 
    tibble(
      mean = mean_x,
      sd = sd_x
    )
  
  return(out_df)
}

mean_and_sd(x_vec)
```


## Check stuff using a simulation

```{r}
sim_df = 
  tibble(
    x = rnorm(30, 10, 5)
  )

sim_df %>% 
  summarize(
    mean = mean(x),
    sd = sd(x)
  )

```

Simulation function to check sample mean and sd
```{r}

#you can also set default value in the input of the function, and can also change the value when you use the function
# eg sim_mean_sd = function(samp_size = 30, true_mean = 5, true_sd = 3)


sim_mean_sd = function(samp_size, true_mean, true_sd){  
  sim_df = 
  tibble(
    x = rnorm(samp_size, true_mean, true_sd)
  )

out_df =
  sim_df %>% 
  summarize(
    mean = mean(x),
    sd = sd(x)
  )

  return(out_df)

}

sim_mean_sd(samp_size = 30, true_mean = 4, true_sd = 12)
sim_mean_sd(true_mean = 4, true_sd = 12, samp_size = 30) #if you are naming, its ok to use any sequence; 

```


#revisit LoTR words

```{r}
fellowship_df = 
  read_excel("data/LotR_Words.xlsx", range = "B3:D5") %>% 
  mutate(movie = "fellowship")

two_towers_df = 
  read_excel("data/LotR_Words.xlsx", range = "F3:H6") |>
  mutate(movie = "two_towers")

return_king_df = 
  read_excel("data/LotR_Words.xlsx", range = "J3:L6") |>
  mutate(movie = "return_king")


read_lotr = function(x, y){
  out_df = 
  read_excel("data/LotR_Words.xlsx", range = x) %>% 
    mutate(movie = y)
  
  return(out_df)
}
read_lotr("B3:D6","fellowship")

lotr_tidy = bind_rows(fellowship_ring, two_towers, return_king) |>
  janitor::clean_names() |>
  pivot_longer(
    female:male,
    names_to = "sex",
    values_to = "words") |> 
  mutate(race = str_to_lower(race)) |> 
  select(movie, everything()) 
```

```{r}
lotr_import = function(cell_range, movie_title){
  
  movie_df = 
  read_excel("data/LotR_Words.xlsx", range = cell_range) %>% 
  mutate(movie = movie_title) %>% 
  janitor::clean_names() %>% 
  pivot_longer(
    female:male,
    names_to = "sex",
    values_to = "words") %>% 
  select(movie, everything()) 
  
  return(movie_df)
}

lotr_import("B3:D6", "fellowship")


lotr_df = 
  bind_rows(
    lotr_import("B3:D6", "fellowship"),
    lotr_import("F3:H6", "two_towers"),
    lotr_import("J3:L6", "return_king")
  )
```


# NSDUH
```{r}
nsduh_url = "http://samhda.s3-us-gov-west-1.amazonaws.com/s3fs-public/field-uploads/2k15StateFiles/NSDUHsaeShortTermCHG2015.htm"

nsduh_html = read_html(nsduh_url)

marj_table = 
  nsduh_html %>% 
  html_table() %>% 
  nth(1) %>% 
  slice(-1) %>% 
  mutate(drug = "marj")

cocaine_table = 
  nsduh_html %>% 
  html_table() %>% 
  nth(4) %>% 
  slice(-1) %>% 
  mutate(drug = "cocaine")

heroin_table = 
  nsduh_html %>% 
  html_table() %>% 
  nth(5) %>% 
  slice(-1) %>% 
  mutate(drug = "heroin")
```


```{r}
drug_table = function(html, number, drug){
  
  drug_df = 
  html %>% 
  html_table() %>% 
  nth(number) %>% 
  slice(-1) %>% 
  mutate(drug = drug) %>% 
    select(-contains("P Values"))
  
  return(drug_df)
}

drug_table(html = nsduh_html, 1, "marj")


source("source/nsduh_table_format.R")
bind_rows(
  drug_table(html = nsduh_html, 1, "marj"),
  drug_table(html = nsduh_html, 4, "cocaine"),
  drug_table(html = nsduh_html, 5, "heroin")
)
```

